### ISSUE TITLE
[TODO]: Finish analog deadzone/sensitivity, motors

### ISSUE THREAD

**Issue by 987123879113** [987123879113/pcsx2#7]
The configuration side of things is done but the backend where it's actually used isn't.

- [ ] Analog deadzone impl
- [ ] Analog sensitivity impl
- [ ] Motor impl
  - [ ] Thrill Drive 3 handle
  - [ ] Thrill Drive 3 seatbelt
